spring.application.name=meditrust-patient-api
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/meditrust
spring.datasource.username=meditrust
spring.datasource.password=meditrust
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
